version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "indices.breaker.total.limit=90%"
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=Elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - screening-net

  kibana:
    image: kibana:7.17.0
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: "Elastic"
    ports:
      - "5601:5601"
    networks:
      - screening-net

volumes:
  es_data:
    driver: local

networks:
  screening-net:
    external: true